import type { Metadata } from "next";
import { Funnel_Sans, Inter } from "next/font/google";
import "./globals.css";

const funnel_sans = Funnel_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${funnel_sans.variable} ${inter.variable} antialiased bg-background text-foreground`}>{children}</body>
    </html>
  );
}
